### ISSUE TITLE
TextureView size can be less than Camera Preview size

### ISSUE THREAD

**Issue by anonym24** [lll-01/VideoRecorder#10]
For example my phone display size is 1280x720, but camera supports 1920x1080 resolution and I would like to use 

So `onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height)` would return 1280 width and 720 height 

set this view to `new DefaultCameraPreview(mTextureView);`

and when I set FullHD resolution for Camera `cameraParameters.setPreviewSize(1920, 1080);` it doesn't show full frame on phone screen (and mb also on recorded video), it looks like it's zoomed (not all 1920x1080 frame is visible to me, only cropped 1280x720 center)

**Comment by erleizh** [comment]
@anonym24  https://github.com/lll-01/VideoRecorder/blob/912108ceefc273cbb7bd42c3ad185f86d710ad6c/VideoRecorderCore/src/main/java/com/erlei/videorecorder/gles/DefaultCoordinateTransform.java#L51

**Comment by anonym24** [comment]
what about next code? I removed scale code

```
    public float[] getMVPMatrixOES() {

        float[] modelMatrix = new float[16];
        Matrix.setIdentityM(modelMatrix, 0);

        return modelMatrix;

    }
```

I tried this and it works ok 

if camera preview is 1280x720 and textureview is 1920x1080 it seems automatically fills 1280x720 frame into 1920x1080 view

if camera preview is 1920x1080 and textureview is 1280x720 it seems automatically fills the whole 1920x1080 frame into 1280x720 view

**Comment by erleizh** [comment]
删除比例代码会有问题 ， 在View比例和相机比例不一致的时候会变形 ，你可以将预览窗口改成正方形试试

**Comment by erleizh** [comment]
@anonym24 对的 ，会自动填充 ， 现在是类似于 ImageView CENTER_CROP

**Comment by anonym24** [comment]
Also what about `MediaCodec`'s `Surface`? (`mSurface = mMediaCodec.createInputSurface()`)

I want preview 1920x1080 for example but record video at 1280x720 (`MediaFormat.createVideoFormat(MIME_TYPE, 1280, 720;`)

Recorded Video is zoomed (center cropped from 1920x1080)

**Comment by anonym24** [comment]
My idea that `CameraGLRenderer's  mSurfaceSize ` should equal `Camera`preview size, for example 1920x1080 preview

```
@Override
    public Size getSurfaceSize() {
       return mCameraWrapper.getPreviewSize(); // instead of mCameraPreview.getSurfaceSize()
    }
```

TextureView can be for example 1280x720 and we should fill 1920x1020 frames to that 1280x720 view

Record size can be for example 720x405, so we should fill 1920x1020 frames to 720x405 MediaCodec surface

or record can be 1920x1080 (equals Camera preview) if user wants to record in FullHD quality

**Comment by anonym24** [comment]
it just makes more sense when camera preview size and `CameraGLRenderer's mSurfaceSize` equals or bigger than record size
it would not make sense to record video 1920x1080 if camera preview size or `CameraGLRenderer's mSurfaceSize` is 1280x720, so we should not set `CameraGLRenderer's mSurfaceSize`  based on TextureView size or any other view size, we should set `CameraGLRenderer's mSurfaceSize` based on camera preview size

**Comment by anonym24** [comment]
I solved problem with TextureSurface view size:
we can use `TextureSurface's surfaceTexture.setDefaultBufferSize(cameraPreviewWidth, cameraPreviewHeight);`

Now only `MediaCodec's surface` size is left, need to somehow fill Camera Preview Size into it if their sizes are different

and `CameraGLRenderer's mSurfaceSize` is always have to == Camera Preview Size

**Comment by anonym24** [comment]
To fix video size (`MediaCodec's surface`) we can use `GLES20.glViewport(...)`

Now I solved all my problems:)
