### ISSUE TITLE
How rotate preview and video

### ISSUE THREAD

**Issue by ToysoftInc** [lll-01/VideoRecorder#17]
Is there a way to rotate the preview and saved video say 90 degree?

**Comment by erleizh** [comment]
You can try ` public CameraBuilder setDisplayOrientation(int displayOrientation)` but there are probably problems

You can look at

https://github.com/erleizh/VideoRecorder/blob/c954462bb24edafbb4929572f3a2e48478d4c7ce/VideoRecorderCore/src/main/java/com/erlei/videorecorder/gles/CoordinateTransform.java#L165
https://github.com/erleizh/VideoRecorder/blob/c954462bb2/VideoRecorderCore/src/main/java/com/erlei/videorecorder/gles/DefaultCoordinateTransform.java

**Comment by ToysoftInc** [comment]
would be nice if you can update the library with the following new features:

- Update app to API 33 and support for Android OS 11+
- Add rotation for preview and recorded video
- Mirror front camera

thank you

**Comment by erleizh** [comment]
> would be nice if you can update the library with the following new features:
> 
> * Update app to API 33 and support for Android OS 11+
> * Add rotation for preview and recorded video
> * Mirror front camera
> 
> thank you

1. I will submit a commit that will update the compilation of 72c91280 (feat: update agp_version to 7.2.0, targetSdkVersion to 31, and specify NDK version as 22.1.7171670). However, this commit does not handle API compatibility, and I do not have a higher version phone on hand to confirm whether it can run properly. (Other than the file sandbox, there should be no other effects, just use the sandbox path.)

2. Regarding video rotation, I am not sure if there is only a compatibility issue with Samsung phones on your end, or if you need a feature to specify the video rotation direction. 
3. Video mirroring (flipping), the default effect should already have been flipped. 

You can add the following key code for video rotation and mirroring:
```
rotate(modelMatrix,90);
flip(modelMatrix,true,false);
```
at the specified location in the code:

https://github.com/erleizh/VideoRecorder/blob/c954462bb24edafbb4929572f3a2e48478d4c7ce/VideoRecorderCore/src/main/java/com/erlei/videorecorder/gles/DefaultCoordinateTransform.java#L43

If you need to also rotate the CanvasOverlayEffect, you can add the following code:
```
CoordinateTransform.rotate(mMVPMatrix2D,90);
```
at the specified location in the code:

https://github.com/erleizh/VideoRecorder/blob/c954462bb24edafbb4929572f3a2e48478d4c7ce/VideoRecorderCore/src/main/java/com/erlei/videorecorder/effects/CanvasOverlayEffect.java#L131



That's all the help I can provide. Good luck!

**Comment by ToysoftInc** [comment]
thank you
