### ISSUE TITLE
Capture picture is blank and only 7k

### ISSUE THREAD

**Issue by ToysoftInc** [lll-01/VideoRecorder#18]
When I do a single tap to capture the picture it only saves 7k and it is blank.
I'm using Samsung S10 Android OS13.

It did capture successfully once.

**Comment by erleizh** [comment]
> 当我单击以捕获图片时，它只保存 7k，而且它是空白的。 我正在使用三星 S10 Android OS13。
> 
> 它确实成功捕获了一次。

You are using mCamera.takePicture ？

**Comment by ToysoftInc** [comment]
I'm using the master branch and have not modified any code.  When I tap on the circle button to take picture it somethings do not save the picture. 

https://github.com/erleizh/VideoRecorder/blob/c954462bb24edafbb4929572f3a2e48478d4c7ce/app/src/main/java/com/erlei/videorecorder/fragment/MultiPartRecorderFragment.java#L139

**Comment by erleizh** [comment]
> 我正在使用 master 分支并且没有修改任何代码。当我点击圆圈按钮拍照时，有些东西不保存图片。
> 
> https://github.com/erleizh/VideoRecorder/blob/c954462bb24edafbb4929572f3a2e48478d4c7ce/app/src/main/java/com/erlei/videorecorder/fragment/MultiPartRecorderFragment.java#L139

Maybe it's just too slow here.
https://github.com/erleizh/VideoRecorder/blob/c954462bb24edafbb4929572f3a2e48478d4c7ce/VideoRecorderCore/src/main/java/com/erlei/videorecorder/recorder/VideoRecorder.java#L300

**Comment by ToysoftInc** [comment]
ok. thx 

:(

**Comment by erleizh** [comment]
> ok. thx
> 
> :(

In case you didn't see it, I declared in REDEME.md that this project contains many bugs and is not suitable for production use.
If you want to keep trying, maybe you can check out the following link

PixelBufferObject

[glReadPixels](https://www.khronos.org/opengl/wiki/GLAPI/glReadPixels)

[Android 关于美颜/滤镜 利用PBO从OpenGL录制视频](https://www.jianshu.com/p/3bc4db687546)

[gl_pbo](http://www.songho.ca/opengl/gl_pbo.html)

[fast-pixel-transfers-with-pixel-buffer-objects](http://roxlu.com/2014/048/fast-pixel-transfers-with-pixel-buffer-objects)

[像素缓冲对象](https://www.khronos.org/opengl/wiki/Pixel_Buffer_Object)

[像素传输](https://www.khronos.org/opengl/wiki/Pixel_Transfer#Pixel_transfer_parameters)
