### ISSUE TITLE
Draw text on frames before recording

### ISSUE THREAD

**Issue by anonym24** [lll-01/VideoRecorder#2]
I was working a little bit with OpenGLES frame processing:

https://github.com/google/grafika/issues/74#issuecomment-406852804

I encoded a video with text, though text had a black background

Do you have plans to add Draw Text support in this project?

Mb we should use _android-openGL-canvas_ lib https://github.com/ChillingVan/android-openGL-canvas to draw on GL Texture (if it'll make things easier)

Also there is _AndroidInstantVideo_ https://github.com/ChillingVan/AndroidInstantVideo
It draws text on preview, but unfortunately it doesn't draw text on a recorded video
And I created two issues there:
https://github.com/ChillingVan/AndroidInstantVideo/issues/14
https://github.com/ChillingVan/AndroidInstantVideo/issues/15

**Comment by erleizh** [comment]
@anonym24 我预备以这种方式支持 [media-for-mobile](https://github.com/INDExOS/media-for-mobile/blob/master/effects/src/main/java/org/m4m/effects/TextOverlayEffect.java) , 
不过近期内不会考虑这个 ,

**Comment by anonym24** [comment]
@lll-01 
please English:)

yes I know about media-for-mobile

but class TextOverlayEffect.java extends many other classes
so it's quite difficult to understand how it works

**Comment by anonym24** [comment]
I made a sample (edited next project) https://github.com/ChillingVan/AndroidInstantVideo
It records a video and draw text on every frames

But video recording itself is very bad implemented (drops a lot of frames, isn't smooth)

Do you have any ideas how to copy their draw filters (they use bitmap/canvas somehow with GLES) to your project?

**Comment by anonym24** [comment]
I made a sample (edited next project) https://github.com/ChillingVan/AndroidInstantVideo
It records a video and draw text on every frames

But video recording itself is very bad implemented (drops a lot of frames, isn't smooth)

Do you have any ideas how to copy their draw filters (they use bitmap/canvas somehow with GLES) to your project?

[AndroidInstantVideoDrawText.zip](https://github.com/lll-01/VideoRecorder/files/2231748/AndroidInstantVideoDrawText.zip)

**Comment by erleizh** [comment]
@anonym24 Sorry, I don't know English. I think you need the google chrome translation plugin.

I won't use https://github.com/ChillingVan/android-openGL-canvas
I have already figured out how to implement video watermarking. And ready to support the canvas api, the approximate implementation method please see [OverlayEffect.java](https://github.com/INDExOS/media-for-mobile/blob/master/effects/src/main/java/org/m4m/effects/OverlayEffect.java) , [VideoEffect.java](https://github.com/INDExOS/media-for-mobile/blob/master/android/src/main/java/org/m4m/android/graphics/VideoEffect.java)

by
```
    Interface CameraTextureCallback {
        /**
         * @param size - the size of the frame
         */
        Void onCameraViewStarted(Size size);

        /**
         * This method is invoked when camera preview has been stopped for some reason.
         * No frames will be delivered via onCameraFrame() callback after this method is called.
         */
        Void onCameraViewStopped();

        /**
         * This method is invoked when a new preview frame from Camera is ready.
         * <p>
         * <p>
         * This method is invoked when camera preview has started. After this method is invoked
         * the frames will startRecord to be delivered to client via the onCameraFrame() callback.
         *
         * @param texIn - the OpenGL texture ID that contains frame in RGBA format
         * @param texOut - the OpenGL texture ID that can be used to store modified frame image t display
         * @return `true` if `texOut` should be displayed, `false` - to show `texIn`
         */
        Boolean modify(int texIn, int texOut);
    }
```
`modify` method `GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, GLES20.GL_RGBA, bitmap, 0)`;

**Comment by anonym24** [comment]
@lll-01 ok, thanks
so are you planning add support for this soon?

**Comment by erleizh** [comment]
@anonym24 develop 分支上已经有这个功能了 , 
```
        mEffectsManager = new EffectsManager();
        mEffectsManager.addEffect(new CanvasOverlayEffect() {
            private FPSCounterFactory.FPSCounter1 mCounter;
            Paint mPaint;

            @Override
            public void prepare(Size size) {
                super.prepare(size);
                mPaint = new Paint();
                mPaint.setColor(Color.YELLOW);
                mPaint.setAlpha(230);
                mPaint.setTextSize(40);
                mPaint.setStyle(Paint.Style.FILL);
                mPaint.setAntiAlias(true);

                mCounter = new FPSCounterFactory.FPSCounter1();
            }

            @Override
            protected void drawCanvas(Canvas canvas) {
                canvas.drawText(String.format(Locale.getDefault(), "%.2f", mCounter.getFPS()), canvas.getWidth() / 2, canvas.getHeight() / 2, mPaint);
            }
        });

    VideoRecorder.Builder builder = new VideoRecorder.Builder(cameraPreview)
                .setCallbackHandler(new CallbackHandler())
                .setLogFPSEnable(false)
                .setCameraBuilder(cameraBuilder)
                .setDrawTextureListener(mEffectsManager)
                .setOutPutPath(new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM), File.separator + "VideoRecorder").getAbsolutePath())
                .setFrameRate(30)
                .setChannelCount(1);

```

**Comment by anonym24** [comment]
cannot resolve symbol `EffectsManager`

cannot resolve method `setDrawTextureListener`

**Comment by anonym24** [comment]
Thanks I'll try it

**Comment by erleizh** [comment]
@anonym24 你如果需要更高的性能的话 ， 可以自己封装一个Sprite ， 类似于[Sprite2d](https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/gles/Sprite2d.java) 直接将水印绘制到 fbo 里面

**Comment by anonym24** [comment]
I notice FPS dropping with   ` .setDrawTextureListener(mEffectsManager)`

I set 30000, 30000 (min,max) for my camera and with `   .setDrawTextureListener(mEffectsManager)`

it records video at 18-24 fps

When I comment this line `//.setDrawTextureListener(mEffectsManager)`

It record video at 30 fps

**Comment by erleizh** [comment]
我现在的实现是创建了一个预览窗口大小的bitmap ， 但是实际上只使用了一小部分 ， 完全没有必要创建这么大的bitmap ，这会导致 texImage2D 耗时太长 。 

你可以尝试减小bitmap的尺寸 。 然后调整bitmap的位置 。
或者提前将bitmap转换为texture  。

如果你的水印是固定不变的 ，不需要一直重绘bitmap ，那么只需在prepare的时候要 texImage2D 一次就可以了 ， 那样将会大大加快速度

**Comment by anonym24** [comment]
I still need dynamic text, so yes one of the solutions it's use smaller bitmap

But do these 6-11 milliseconds (ms) really influence performance that much?



```
long startTime = SystemClock.elapsedRealtime();
GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, GLES20.GL_RGBA, mCanvasBitmap, 0);
Log.i(TAG, "texImage2D " + (SystemClock.elapsedRealtime() - startTime) + " ms");
```

```
08-09 17:05:09.004 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.042 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 9 ms
08-09 17:05:09.078 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 9 ms
08-09 17:05:09.105 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:09.139 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.173 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:09.209 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 8 ms
08-09 17:05:09.239 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:09.274 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.307 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:09.341 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.377 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 8 ms
08-09 17:05:09.409 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 8 ms
08-09 17:05:09.441 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.475 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.510 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 8 ms
08-09 17:05:09.542 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.575 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:09.608 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:09.643 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.678 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.711 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:09.744 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.781 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 10 ms
08-09 17:05:09.812 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.844 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:09.878 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.912 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:09.945 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:09.978 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:10.012 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:10.065 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 25 ms
08-09 17:05:10.087 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 13 ms
08-09 17:05:10.117 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:10.148 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 9 ms
08-09 17:05:10.179 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:10.217 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 10 ms
08-09 17:05:10.247 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 5 ms
08-09 17:05:10.283 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 8 ms
08-09 17:05:10.317 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 9 ms
08-09 17:05:10.349 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 8 ms
08-09 17:05:10.382 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:10.417 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 9 ms
08-09 17:05:10.448 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 6 ms
08-09 17:05:10.484 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 9 ms
08-09 17:05:10.521 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 11 ms
08-09 17:05:10.550 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms
08-09 17:05:10.585 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 8 ms
08-09 17:05:10.618 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 9 ms
08-09 17:05:10.657 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 9 ms
08-09 17:05:10.701 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 11 ms
08-09 17:05:10.723 10506-10704/com.erlei.videorecorder I/CanvasOverlayEffect: texImage2D 7 ms

```

Also it draws text on TexturePreview, mb it influences performance, as I understand it should only draw texture for video frames but not for preview

```
    @Override
    public int applyEffect(int fbo, int textureIdIn) {
        mCanvas.drawColor(Color.TRANSPARENT, PorterDuff.Mode.CLEAR);

        mCanvas.drawText("test", 150, 150, mPaint);

        GLES20.glEnable(GLES20.GL_BLEND);
        GLES20.glBlendFunc(GLES20.GL_ONE, GLES20.GL_ONE_MINUS_SRC_ALPHA);

        GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, mTexture);

        long startTime = SystemClock.elapsedRealtime();
        GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, GLES20.GL_RGBA, mCanvasBitmap, 0);
        Log.i(TAG, "texImage2D " + (SystemClock.elapsedRealtime() - startTime) + " ms");

        mRender.drawTexture(mTexture, fbo);

        GLES20.glDisable(GLES20.GL_BLEND);

        return textureIdIn;
    }
```

![123](https://user-images.githubusercontent.com/8851301/43905739-597d5e5e-9bfa-11e8-9925-802fddf2deb5.png)

**Comment by erleizh** [comment]
[RecordFBOActivity](https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/RecordFBOActivity.java)

三种方法 , 我是用的是第一种 , 相当于录制的时候每帧都会  GLUtils.texImage2D 两次  
@anonym24

**Comment by anonym24** [comment]
I edited your project (I removed OpenGL code) to test how fast MediaCodec Canvas could work

https://github.com/anonym24/VideoRecorderMediaCodecCanvas

I copied some OpenCV4Android Java classes which implement great optimization for frames from `onPreviewFrame` (they use separate thread for processing and they store two frames)

onPreviewFrame
https://github.com/anonym24/VideoRecorderMediaCodecCanvas/blob/master/app/src/main/java/com/erlei/videorecorder/camera/JavaCameraView.java#L312

Runnable Thread which processes frames
https://github.com/anonym24/VideoRecorderMediaCodecCanvas/blob/master/app/src/main/java/com/erlei/videorecorder/camera/JavaCameraView.java#L348

Then I use callback to send Bitmap to your Video Recorder
Callback
https://github.com/anonym24/VideoRecorderMediaCodecCanvas/blob/master/app/src/main/java/com/erlei/videorecorder/camera/JavaCameraView.java#L376

https://github.com/anonym24/VideoRecorderMediaCodecCanvas/blob/master/app/src/main/java/com/erlei/videorecorder/fragment/VideoRecorderFragment.java#L70

and finally DrawMethod

https://github.com/anonym24/VideoRecorderMediaCodecCanvas/blob/master/app/src/main/java/com/erlei/videorecorder/recorder/VideoRecorder.java#L97

and it works pretty fast even with FullHD (1920x1080), smooth fps

but one issue it may not work for all devices 

I found out that it doesn't work ok for Meizu devices. Video isn't always playable and video players play recorded video very fast. Mb it's has something to do with `frameAvailableSoon`, `drain` methods (timestamps and other things) 
 https://github.com/anonym24/VideoRecorderMediaCodecCanvas/blob/master/app/src/main/java/com/erlei/videorecorder/recorder/VideoRecorder.java#L99
https://github.com/anonym24/VideoRecorderMediaCodecCanvas/blob/master/app/src/main/java/com/erlei/videorecorder/encoder/MediaEncoder.java#L106
https://github.com/anonym24/VideoRecorderMediaCodecCanvas/blob/master/app/src/main/java/com/erlei/videorecorder/encoder/MediaEncoder.java#L119

----------------------------------------


About your project (with OpenGL)

Mb we should use similar Thread frame optimization and store two frames

onPreviewFrame
https://github.com/anonym24/VideoRecorderMediaCodecCanvas/blob/master/app/src/main/java/com/erlei/videorecorder/camera/JavaCameraView.java#L312

Runnable Thread which processes frames
https://github.com/anonym24/VideoRecorderMediaCodecCanvas/blob/master/app/src/main/java/com/erlei/videorecorder/camera/JavaCameraView.java#L348

Mb we need to do similar with your RenderThread' `onFrameAvailable `https://github.com/lll-01/VideoRecorder/blob/master/VideoRecorderCore/src/main/java/com/erlei/videorecorder/recorder/RenderThread.java#L152

Because in my project I convert byte[] array to Bitmap (it takes 8-13 ms) and it doesn't influence video recording performance, it's still smooth because separate synchronized Thread is used

**Comment by erleizh** [comment]
@anonym24 关于视频播放的问题 ， 应该是音频帧的时间戳有问题， 你应该看看[AudioVideoRecordingSample](https://github.com/saki4510t/AudioVideoRecordingSample)
事实上这个项目里面的编码部分就来自于它 ，你可以看到有`encoder1 `和 `encoder` 两个包 ， encoder 包是我自己实现的 ，但是对于某些手机会有问题 ，encoder1是复制的 AudioVideoRecordingSample ，它可以完美的工作

关于GLUtils.texImage2D 导致的问题 ， 本来我是计划抽时间修改这里的代码  ，[grafika](https://github.com/google/grafika) [RecordFBOActivity](https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/RecordFBOActivity.java)  这个里面演示了三种方法 ，换一种应该会有比较大的提升 ， 至少不用 draw 两次 ， 只需要一个复制缓冲区的开销

**Comment by anonym24** [comment]
I tried to replace _encoder_ with _encoder1_ in my test recorder without OpenGL

Sample: https://github.com/anonym24/VideoRecorderMediaCodecCanvasEncoder1

It starts video recording ok

But it fails to stop video recording correctly

```

08-12 21:35:34.234 7485-7854/com.erlei.videorecorder E/MPEG4Writer: The number of recorded samples is 0
08-12 21:35:34.234 7485-7853/com.erlei.videorecorder I/MPEG4Writer: Received total/0-length (7/0) buffers and encoded 7 frames. - Audio
08-12 21:35:34.234 7485-7827/com.erlei.videorecorder D/MPEG4Writer: Audio track source stopping
    Audio track source stopped
08-12 21:35:34.234 7485-7854/com.erlei.videorecorder W/MPEG4Writer: 0-duration samples found: 1
08-12 21:35:34.234 7485-7853/com.erlei.videorecorder I/MPEG4Writer: Audio track drift time: 0 us
08-12 21:35:34.234 7485-7854/com.erlei.videorecorder W/MPEG4Writer: 0-duration samples found: 1
08-12 21:35:34.234 7485-7854/com.erlei.videorecorder I/MPEG4Writer: Received total/0-length (0/0) buffers and encoded 0 frames. - Video
08-12 21:35:34.234 7485-7827/com.erlei.videorecorder D/MPEG4Writer: Audio track stopped
    Video track stopping
    Video track source stopping
    Video track source stopped
08-12 21:35:34.235 7485-7827/com.erlei.videorecorder D/MPEG4Writer: Video track stopped
    Duration from tracks range is [0, 274956] us
    Stopping writer thread
08-12 21:35:34.235 7485-7852/com.erlei.videorecorder D/MPEG4Writer: 0 chunks are written in the last batch
08-12 21:35:34.235 7485-7827/com.erlei.videorecorder D/MPEG4Writer: Writer thread stopped
08-12 21:35:34.235 7485-7827/com.erlei.videorecorder E/VideoRecorder-VideoRecorder: MediaMuxer stopped: errorjava.lang.IllegalStateException: Failed to stop the muxer
08-12 21:35:34.235 7485-7827/com.erlei.videorecorder W/System.err: java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:239)
08-12 21:35:34.236 7485-7827/com.erlei.videorecorder W/System.err:     at com.erlei.videorecorder.videorecorder.encoder1.MediaMuxerWrapper.stop(MediaMuxerWrapper.java:148)
        at com.erlei.videorecorder.videorecorder.encoder1.MediaEncoder.release(MediaEncoder.java:227)
        at com.erlei.videorecorder.videorecorder.encoder1.MediaAudioEncoder.release(MediaAudioEncoder.java:100)
        at com.erlei.videorecorder.videorecorder.encoder1.MediaEncoder.run(MediaEncoder.java:150)
        at java.lang.Thread.run(Thread.java:818)
08-12 21:35:34.236 7485-7827/com.erlei.videorecorder E/MediaMuxer: stop() is called in invalid state 3
08-12 21:35:34.236 7485-7827/com.erlei.videorecorder W/System.err: java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:239)
        at android.media.MediaMuxer.release(MediaMuxer.java:360)
        at com.erlei.videorecorder.videorecorder.encoder1.MediaMuxerWrapper.stop(MediaMuxerWrapper.java:157)
        at com.erlei.videorecorder.videorecorder.encoder1.MediaEncoder.release(MediaEncoder.java:227)
08-12 21:35:34.237 7485-7827/com.erlei.videorecorder W/System.err:     at com.erlei.videorecorder.videorecorder.encoder1.MediaAudioEncoder.release(MediaAudioEncoder.java:100)
        at com.erlei.videorecorder.videorecorder.encoder1.MediaEncoder.run(MediaEncoder.java:150)
        at java.lang.Thread.run(Thread.java:818)
08-12 21:35:34.237 7485-7827/com.erlei.videorecorder D/VideoRecorder-VideoRecorder: MediaMuxer stopped:
    Encoder thread exiting

```

Do you know what could be the issue?

**Comment by erleizh** [comment]
@anonym24 https://stackoverflow.com/search?q=Failed+to+stop+the+muxer

**Comment by anonym24** [comment]
found out the issue - I called `mSurface = mVideoEncoder.getSurface();` before ` mMuxer.prepare();`

**Comment by anonym24** [comment]
I tried to edit https://github.com/ChillingVan/AndroidInstantVideo to work without OpenGL but MediaCodec canvas only

it finally worked ok 

though lockHardwareCanvas is available only from 23, just lockCanvas isn't going to work ok

so for 4 (KitKat), 5 (Lollipop) it's better to use your project with OpenGL and somehow optimize Canvas API performance

**Comment by erleizh** [comment]
[https://github.com/google/grafika/issues/74](https://github.com/google/grafika/issues/74)
