### ISSUE TITLE
Pause Resume request

### ISSUE THREAD

**Issue by anonym24** [lll-01/VideoRecorder#5]
Would be great to pause video recording temporary and then resume recording later (e.g, after 5-10 seconds)

For example we won't feed anything (audio or video) to encoder about 5-10 seconds

But there could be a problem with timestamps (e.g. we were recording 10 seconds but it during playback in video player it says 15 seconds)

I suggest subtract this not recording count milliseconds (the time we wasn't feed any data)

```
    protected long getPTSUs() {
		long result = System.nanoTime() / 1000L;
		// presentationTimeUs should be monotonic
		// otherwise muxer fail to write
		if (result < prevOutputPTSUs)
			result = (prevOutputPTSUs - result) + result;
		return result - notRecordingTimeUS;
    }

	public void setNotRecordingTimeUS(long notRecordingTimeUS) {
		this.notRecordingTimeUS = notRecordingTimeUS; // e.g. subtract 5 seconds (the time we wasn't feed any video/audio to encoders)
	}

	private long notRecordingTimeUS;
```

**Comment by erleizh** [comment]
@anonym24 你的想法是对的 ，这样可以做到暂停录制 ， 但是它不能删除上一段 ，不过这个功能有必要加到VideoRecordCore 里面 。 如果有时间的话 ，
